# -*- coding: utf-8 -*-
"""bscs25047, bscs25009_FPROJ_PHASE_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bBmuG4PzkxF2JaDNW2-O7-VNDWM5DwZD
"""

# Cell 1 — Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

print("✅ Google Drive mounted successfully.")

# Cell 2 — Connect to the airline database from Google Drive
import sqlite3

DB_PATH = '/content/drive/MyDrive/airline_management.db'

conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()
cursor.execute("PRAGMA foreign_keys = ON;")

print("✅ Connected to database:", DB_PATH)

# Fix flight numbers
cursor.execute("UPDATE Flights SET flight_number = 'PK301' WHERE flight_number = 'PK301-A'")
cursor.execute("UPDATE Flights SET flight_number = 'PK303' WHERE flight_number = 'PK301-B'")  # PK303 instead
conn.commit()

# Verify
cursor.execute("SELECT flight_id, flight_number FROM Flights")
for row in cursor.fetchall():
    print(row)
print("✅ Flight numbers fixed.")

# Cell 3 — Install Required Libraries
!pip install -q langchain
!pip install -q langchain-groq
!pip install -q langchain-core

print("✅ All libraries installed successfully.")

# Cell 4 — Import & Verify Installations
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import SystemMessage, HumanMessage
import os

print("✅ All imports successful.")

from google.colab import userdata
GROQ_API_KEY = userdata.get("GROQ_API_KEY")

llm = ChatGroq(
    model="llama-3.3-70b-versatile",  # ← updated model name
    api_key=GROQ_API_KEY,
    temperature=0,
)
print("✅ Groq LLM initialized successfully.")
print(f"   Model : {llm.model_name}")
print(f"   Temp  : {llm.temperature}")

# ============================================================
# Cell 6 — Metadata Injection
# Purpose: Define the full database schema as a string that
#          will be prepended to every prompt sent to the LLM.
#          This tells the model exactly what tables and columns
#          exist so it can generate correct SQL queries.
# ============================================================

DB_SCHEMA = """
You are working with a SQLite database for Flight Operations & Route Analytics.
The database is named: airline_management.db

TABLE DEFINITIONS:
==================

1. Airports
   - airport_id   INTEGER  PRIMARY KEY
   - iata_code    TEXT     NOT NULL  (e.g. 'KHI', 'LHE', 'ISB')
   - name         TEXT     NOT NULL
   - city         TEXT     NOT NULL
   - country      TEXT     NOT NULL

2. Aircraft
   - aircraft_id      INTEGER  PRIMARY KEY
   - registration_no  TEXT     NOT NULL UNIQUE
   - model            TEXT     NOT NULL  (e.g. 'Boeing 737', 'Airbus A320')
   - total_seats      INTEGER  NOT NULL
   - status           TEXT     NOT NULL  (e.g. 'Active', 'Maintenance', 'Retired')

3. Pilots
   - pilot_id          INTEGER  PRIMARY KEY
   - full_name         TEXT     NOT NULL
   - license_number    TEXT     NOT NULL UNIQUE
   - experience_years  INTEGER  NOT NULL
   - rank              TEXT     NOT NULL  (e.g. 'Captain', 'First Officer', 'Co-Pilot')

4. Routes
   - route_id                  INTEGER  PRIMARY KEY
   - origin_airport_id         INTEGER  FOREIGN KEY → Airports(airport_id)
   - destination_airport_id    INTEGER  FOREIGN KEY → Airports(airport_id)
   - distance_km               REAL     NOT NULL
   - estimated_duration_min    INTEGER  NOT NULL

5. Flights
   - flight_id        INTEGER  PRIMARY KEY
   - flight_number    TEXT     NOT NULL  (e.g. 'PK301', 'PK502')
   - route_id         INTEGER  FOREIGN KEY → Routes(route_id)
   - aircraft_id      INTEGER  FOREIGN KEY → Aircraft(aircraft_id)
   - departure_time   TEXT     NOT NULL  (stored as ISO datetime string)
   - arrival_time     TEXT     NOT NULL  (stored as ISO datetime string)
   - status           TEXT     NOT NULL  (e.g. 'Scheduled', 'Delayed', 'Cancelled', 'Completed')
   - delay_minutes    INTEGER  DEFAULT 0
   - is_direct        INTEGER  NOT NULL  (1 = direct, 0 = connecting)

6. Passengers
   - passenger_id    INTEGER  PRIMARY KEY
   - full_name       TEXT     NOT NULL
   - passport_number TEXT     NOT NULL UNIQUE
   - nationality     TEXT     NOT NULL
   - email           TEXT     NOT NULL UNIQUE

7. Bookings
   - booking_id    INTEGER  PRIMARY KEY
   - passenger_id  INTEGER  FOREIGN KEY → Passengers(passenger_id)
   - flight_id     INTEGER  FOREIGN KEY → Flights(flight_id)
   - seat_number   TEXT     NOT NULL
   - booking_date  TEXT     NOT NULL  (stored as ISO datetime string)
   - class         TEXT     NOT NULL  (e.g. 'Economy', 'Business', 'First')

8. Crew_Assignments
   - assignment_id  INTEGER  PRIMARY KEY
   - pilot_id       INTEGER  FOREIGN KEY → Pilots(pilot_id)
   - flight_id      INTEGER  FOREIGN KEY → Flights(flight_id)
   - role           TEXT     NOT NULL  (e.g. 'Captain', 'First Officer', 'Co-Pilot')

SCHEMA LINKING — VOCABULARY MAP:
=================================
If the user says "clients", "travelers", or "people"     → use the Passengers table
If the user says "purchases", "tickets", "reservations"  → use the Bookings table
If the user says "crew", "staff", or "workers"           → use the Crew_Assignments table
If the user says "planes" or "jets"                      → use the Aircraft table
If the user says "trips", "journeys", or "paths"         → use the Routes table
If the user says "departures" or "arrivals"              → use the Flights table
QUERY RULES:
=============
- When showing route origins or destinations, ALWAYS JOIN with
  the Airports table twice (once for origin, once for destination)
  to return city names instead of raw airport IDs.
  Example:
  JOIN Airports AS A1 ON Routes.origin_airport_id = A1.airport_id
  JOIN Airports AS A2 ON Routes.destination_airport_id = A2.airport_id
  Then SELECT A1.city AS origin_city, A2.city AS destination_city
"""

print("✅ Database schema metadata defined successfully.")
print(f"   Schema string length: {len(DB_SCHEMA)} characters")

# ============================================================
# Cell 7 — Query Generation
# Purpose: Build the prompt that sends the user's question
#          + the full schema to the LLM and gets back a
#          clean SQLite SELECT query and nothing else.
# ============================================================

from langchain_core.messages import SystemMessage, HumanMessage

def generate_sql(user_input):
    """
    Takes a natural language question from the user,
    combines it with the schema metadata, sends it to
    the LLM, and returns a raw SQL query string.
    """

    # --- System message: tells the LLM what role it plays
    #     and what rules it must follow (no markdown, no
    #     explanation, SELECT only, never fabricate) ----------
    system_message = SystemMessage(content=f"""
You are a SQLite query generator for a Flight Operations database.

{DB_SCHEMA}

STRICT RULES YOU MUST FOLLOW:
1. Return ONLY the raw SQL query — no explanations, no markdown,
   no backticks, no comments. Just the SQL string itself.
2. Only generate SELECT statements. Never write INSERT, UPDATE,
   DELETE, DROP, or any other statement.
3. Use only the exact table and column names defined in the schema above.
4. If the question cannot be answered from the available tables,
   respond with exactly this phrase: CANNOT_ANSWER
5. Never fabricate data or assume values that are not in the schema.
""")

    # --- Human message: the actual question from the user ----
    human_message = HumanMessage(content=f"Question: {user_input}")

    # --- Send both messages to the LLM and get response -----
    response = llm.invoke([system_message, human_message])

    # --- Extract the text content from the response object --
    sql_query = response.content.strip()

    return sql_query


# Quick test to confirm the function works
test_query = generate_sql("List all delayed flights")
print("✅ Query generation function defined successfully.")
print(f"\nTest output for 'List all delayed flights':")
print(test_query)

# ============================================================
# Cell 8 — Safe Execution
# Purpose: Validate that the generated query is a SELECT
#          statement, then execute it safely against the
#          SQLite database and return the results.
# ============================================================

def execute_sql(sql_query):
    """
    Takes the SQL query generated by the LLM, validates it,
    executes it against the database, and returns the results.
    """

    # --- Check 1: Handle CANNOT_ANSWER from the LLM ---------
    # If the LLM couldn't answer the question, return early
    if sql_query.strip().upper() == "CANNOT_ANSWER":
        return None, "I'm sorry, that question cannot be answered from the available data."

    # --- Check 2: Ensure query starts with SELECT ------------
    # Strip whitespace and check the first word
    # This blocks any DROP, DELETE, UPDATE etc. from running
    first_word = sql_query.strip().split()[0].upper()
    if first_word != "SELECT":
        return None, "⚠️ Blocked: Only SELECT queries are allowed."

    # --- Execute the query against the SQLite database -------
    try:
        cursor.execute(sql_query)

        # Fetch all rows from the result set
        rows = cursor.fetchall()

        # Fetch column names from the cursor description
        # This tells us what each column in the result is called
        columns = [description[0] for description in cursor.description]

        # --- Check 3: Handle empty results -------------------
        if not rows:
            return None, "The query ran successfully but returned no results."

        return {"columns": columns, "rows": rows}, None

    except Exception as e:
        # If SQLite throws any error, catch it and return
        # a clean message instead of crashing the program
        return None, f"⚠️ Database error: {str(e)}"


# --- Quick test to confirm the function works ---------------
test_sql = "SELECT * FROM Flights WHERE status = 'Delayed'"
result, error = execute_sql(test_sql)

if error:
    print(f"❌ Error: {error}")
else:
    print("✅ Safe execution function defined successfully.")
    print(f"\n   Columns : {result['columns']}")
    print(f"   Rows returned : {len(result['rows'])}")
    print(f"   First row : {result['rows'][0]}")

# ============================================================
# Cell 9 — Synthesis & Response
# Purpose: Take the raw database result and pass it back to
#          the LLM with an instruction to produce a clean,
#          plain English answer for the user.
# ============================================================

def synthesize_response(user_input, sql_query, result):
    """
    Takes the raw query result and asks the LLM to convert
    it into a friendly, readable plain English answer.
    """

    # --- Format the raw result into a readable string -------
    # We convert the columns + rows into a simple text table
    # so the LLM can read and summarize it clearly
    columns = result["columns"]
    rows = result["rows"]

    # Build a readable version of the results
    formatted_result = f"Columns: {columns}\n"
    formatted_result += f"Total rows returned: {len(rows)}\n\n"
    formatted_result += "Data:\n"
    for row in rows:
        # Pair each column name with its value for clarity
        row_dict = dict(zip(columns, row))
        formatted_result += f"  {row_dict}\n"

    # --- System message: tells LLM its role here ------------
    system_message = SystemMessage(content="""
You are a helpful data analyst assistant.
Your job is to read a raw database query result and write
a clear, friendly plain English summary for a non-technical user.

RULES:
1. Never say "the query returned" or use technical database terms.
2. Speak directly to the user in simple, natural language.
3. If multiple rows exist, summarize them clearly.
4. Never fabricate any data beyond what is provided to you.
5. Keep the answer concise but complete.
""")

    # --- Human message: the question + result to summarize --
    human_message = HumanMessage(content=f"""
The user asked: "{user_input}"
The SQL query used was: {sql_query}

Here are the raw results from the database:
{formatted_result}

Please write a clear plain English answer to the user's question
based strictly on the data above.
""")

    # --- Send to LLM and get the plain English response -----
    response = llm.invoke([system_message, human_message])

    return response.content.strip()


# --- Quick test to confirm the function works ---------------
test_result = {
    "columns": ["flight_id", "flight_number", "status", "delay_minutes"],
    "rows": [(3, "EK202", "Delayed", 45)]
}

answer = synthesize_response(
    user_input="List all delayed flights",
    sql_query="SELECT * FROM Flights WHERE status = 'Delayed'",
    result=test_result
)

print("✅ Synthesis function defined successfully.")
print(f"\nPlain English Answer:")
print(answer)

# ============================================================
# Cell 10 — Main Pipeline Function
# Purpose: Wrap all 3 stages (generate → execute → synthesize)
#          into a single function that accepts a natural
#          language question and returns two things:
#          1. A plain English answer
#          2. The raw SQL query that was generated
# ============================================================

def ask_question(user_input):
    """
    Main pipeline function.
    Input  : a natural language question (string)
    Output : (plain_english_answer, sql_query) — both strings
    """

    print(f"\n{'='*60}")
    print(f"Question: {user_input}")
    print(f"{'='*60}")

    # --- Stage 1: Generate SQL from the question ------------
    print("⏳ Stage 1: Generating SQL query...")
    sql_query = generate_sql(user_input)
    print(f"   Generated SQL: {sql_query}")

    # --- Handle CANNOT_ANSWER before touching the DB --------
    if sql_query.strip().upper() == "CANNOT_ANSWER":
        answer = "I'm sorry, that question cannot be answered from the available data."
        print(f"\n❌ {answer}")
        return answer, "CANNOT_ANSWER"

    # --- Stage 2: Safely execute the query ------------------
    print("⏳ Stage 2: Executing query safely...")
    result, error = execute_sql(sql_query)

    # If execution failed or was blocked, return the error
    if error:
        print(f"\n❌ Execution failed: {error}")
        return error, sql_query

    print(f"   ✅ Query returned {len(result['rows'])} row(s).")

    # --- Stage 3: Synthesize a plain English response -------
    print("⏳ Stage 3: Generating plain English answer...")
    answer = synthesize_response(user_input, sql_query, result)

    print(f"\n✅ Final Answer:")
    print(answer)

    return answer, sql_query


# --- Quick test to confirm the full pipeline works ----------
answer, sql = ask_question("List all delayed flights")

print(f"\n{'='*60}")
print("RETURNED VALUES:")
print(f"{'='*60}")
print(f"\n1. Plain English Answer:\n{answer}")
print(f"\n2. SQL Query:\n{sql}")

# ============================================================
# Cell 11 — Pipeline Testing (All 5 Required Queries)
# Purpose: Test the full ask_question() pipeline against
#          all 5 queries specified in the project brief.
# ============================================================

# List of all 5 test questions
test_questions = [
    "List all delayed flights",                                                          # Simple — single table
    "Which aircraft is assigned to flight PK301?",                                       # 2 table JOIN
    "Which pilot has the most flight assignments?",                                      # Aggregation
    "List all passengers who booked business class tickets",                             # 2 table JOIN
    "Show me the origin and destination of each flight along with the passenger count"   # 3+ table JOIN
]

# Run each question through the full pipeline
for i, question in enumerate(test_questions, 1):
    print(f"\n{'🔷'*30}")
    print(f"TEST {i} of {len(test_questions)}")
    answer, sql = ask_question(question)
    print(f"\n{'🔷'*30}\n")