# -*- coding: utf-8 -*-
"""bscs25047,bscs25009_FPROJ_PHASE_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bxIKS5fY0c_WvqXOOPWcn_f15onpgTEE
"""

import sqlite3
from google.colab import drive
drive.mount('/content/drive')

DB_PATH = '/content/drive/MyDrive/airline_management.db'

conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()

cursor.execute("PRAGMA foreign_keys = ON;")

# 1. Airports Table
cursor.execute('''
CREATE TABLE IF NOT EXISTS Airports (
    airport_id INTEGER PRIMARY KEY AUTOINCREMENT,
    iata_code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    city TEXT NOT NULL,
    country TEXT NOT NULL
)
''')

# 2. Aircraft Table
cursor.execute('''
CREATE TABLE IF NOT EXISTS Aircraft (
    aircraft_id INTEGER PRIMARY KEY AUTOINCREMENT,
    registration_no TEXT UNIQUE NOT NULL,
    model TEXT NOT NULL,
    total_seats INTEGER NOT NULL,
    status TEXT NOT NULL
)
''')

# 3. Pilots Table
cursor.execute('''
CREATE TABLE IF NOT EXISTS Pilots (
    pilot_id INTEGER PRIMARY KEY AUTOINCREMENT,
    full_name TEXT NOT NULL,
    license_number TEXT UNIQUE NOT NULL,
    experience_years INTEGER NOT NULL,
    rank TEXT NOT NULL
)
''')

# 4. Routes Table
cursor.execute('''
CREATE TABLE IF NOT EXISTS Routes (
    route_id INTEGER PRIMARY KEY AUTOINCREMENT,
    origin_airport_id INTEGER NOT NULL,
    destination_airport_id INTEGER NOT NULL,
    distance_km REAL NOT NULL,
    estimated_duration_min INTEGER NOT NULL,
    FOREIGN KEY (origin_airport_id) REFERENCES Airports(airport_id),
    FOREIGN KEY (destination_airport_id) REFERENCES Airports(airport_id)
)
''')

# 5. Flights Table
cursor.execute('''
CREATE TABLE IF NOT EXISTS Flights (
    flight_id INTEGER PRIMARY KEY AUTOINCREMENT,
    flight_number TEXT UNIQUE NOT NULL,
    route_id INTEGER NOT NULL,
    aircraft_id INTEGER NOT NULL,
    departure_time DATETIME NOT NULL,
    arrival_time DATETIME NOT NULL,
    status TEXT NOT NULL,
    delay_minutes INTEGER DEFAULT 0,
    is_direct BOOLEAN DEFAULT 1,
    FOREIGN KEY (route_id) REFERENCES Routes(route_id),
    FOREIGN KEY (aircraft_id) REFERENCES Aircraft(aircraft_id)
)
''')

# 6. Passengers Table
cursor.execute('''
CREATE TABLE IF NOT EXISTS Passengers (
    passenger_id INTEGER PRIMARY KEY AUTOINCREMENT,
    full_name TEXT NOT NULL,
    passport_number TEXT UNIQUE NOT NULL,
    nationality TEXT NOT NULL,
    email TEXT NOT NULL
)
''')

# 7. Bookings (Junction Table: Passengers <-> Flights)
cursor.execute('''
CREATE TABLE IF NOT EXISTS Bookings (
    booking_id INTEGER PRIMARY KEY AUTOINCREMENT,
    passenger_id INTEGER NOT NULL,
    flight_id INTEGER NOT NULL,
    seat_number TEXT NOT NULL,
    booking_date DATE NOT NULL,
    class TEXT NOT NULL,
    FOREIGN KEY (passenger_id) REFERENCES Passengers(passenger_id),
    FOREIGN KEY (flight_id) REFERENCES Flights(flight_id),
    UNIQUE (flight_id, seat_number)
)
''')

# 8. Crew_Assignments (Junction Table: Pilots <-> Flights)
cursor.execute('''
CREATE TABLE IF NOT EXISTS Crew_Assignments (
    assignment_id INTEGER PRIMARY KEY AUTOINCREMENT,
    pilot_id INTEGER NOT NULL,
    flight_id INTEGER NOT NULL,
    role TEXT NOT NULL,
    FOREIGN KEY (pilot_id) REFERENCES Pilots(pilot_id),
    FOREIGN KEY (flight_id) REFERENCES Flights(flight_id)
)
''')

conn.commit()
print("Tables created successfully with constraints.")

# 1. Insert Airports (Real Global Hubs)
airports_data = [
    ('KHI', 'Jinnah International', 'Karachi', 'Pakistan'),
    ('DXB', 'Dubai International', 'Dubai', 'UAE'),
    ('LHR', 'Heathrow Airport', 'London', 'UK'),
    ('JFK', 'John F. Kennedy Intl', 'New York', 'USA'),
    ('SIN', 'Changi Airport', 'Singapore', 'Singapore'),
    ('IST', 'Istanbul Airport', 'Istanbul', 'Turkey'),
    ('DOH', 'Hamad International', 'Doha', 'Qatar'),
    ('HND', 'Haneda Airport', 'Tokyo', 'Japan'),
    ('CDG', 'Charles de Gaulle', 'Paris', 'France'),
    ('ISB', 'Islamabad International', 'Islamabad', 'Pakistan')
]
cursor.executemany("INSERT INTO Airports (iata_code, name, city, country) VALUES (?, ?, ?, ?)", airports_data)

# 2. Insert Aircraft (Real Models)
aircraft_data = [
    ('AP-BMG', 'Boeing 777-300ER', 396, 'Active'),
    ('A6-EEO', 'Airbus A380-800', 517, 'Active'),
    ('G-VNEW', 'Boeing 787-9', 264, 'Active'),
    ('N787AL', 'Boeing 787-8', 242, 'Maintenance'),
    ('9V-SMC', 'Airbus A350-900', 253, 'Active'),
    ('TC-JNN', 'Airbus A330-300', 289, 'Active'),
    ('A7-BEL', 'Boeing 777-200LR', 317, 'Active'),
    ('JA-803A', 'Boeing 787-8', 240, 'Active'),
    ('F-GSPL', 'Boeing 777-300', 381, 'Active'),
    ('AP-BLZ', 'Airbus A320-200', 174, 'Active')
]
cursor.executemany("INSERT INTO Aircraft (registration_no, model, total_seats, status) VALUES (?, ?, ?, ?)", aircraft_data)

# 3. Insert Pilots (Real Names & Experience)
pilots_data = [
    ('Ali Ahmed', 'L-10293', 15, 'Captain'),
    ('Sarah Khan', 'L-44521', 8, 'First Officer'),
    ('James Wilson', 'L-99820', 20, 'Senior Captain'),
    ('Yuki Tanaka', 'L-77631', 12, 'Captain'),
    ('Fatima Al-Sayed', 'L-33412', 6, 'First Officer'),
    ('Jean-Pierre', 'L-11223', 18, 'Captain'),
    ('Robert Brown', 'L-55678', 25, 'Senior Captain'),
    ('Ayesha Malik', 'L-88901', 10, 'First Officer'),
    ('Hassan Raza', 'L-22334', 14, 'Captain'),
    ('Emily Davis', 'L-44556', 5, 'First Officer')
]
cursor.executemany("INSERT INTO Pilots (full_name, license_number, experience_years, rank) VALUES (?, ?, ?, ?)", pilots_data)

# 4. Insert Routes (Linking Airports)
# 1:KHI, 2:DXB, 3:LHR, 4:JFK, 5:SIN, 6:IST, 7:DOH, 8:HND, 9:CDG, 10:ISB
routes_data = [
    (1, 2, 1189, 130), # KHI to DXB
    (2, 3, 5470, 465), # DXB to LHR
    (3, 4, 5540, 480), # LHR to JFK
    (5, 8, 5320, 410), # SIN to HND
    (6, 9, 2210, 210), # IST to CDG
    (10, 1, 1140, 110),# ISB to KHI
    (7, 2, 370, 65),   # DOH to DXB
    (2, 5, 5850, 450), # DXB to SIN
    (4, 3, 5540, 420), # JFK to LHR (Return)
    (9, 6, 2210, 190)  # CDG to IST (Return)
]
cursor.executemany("INSERT INTO Routes (origin_airport_id, destination_airport_id, distance_km, estimated_duration_min) VALUES (?, ?, ?, ?)", routes_data)

# 5. Insert Flights
flights_data = [
    ('PK301-A', 1, 1, '2026-05-01 08:00', '2026-05-01 10:10', 'Scheduled', 0, 0), # Leg 1
    ('PK301-B', 2, 1, '2026-05-01 12:00', '2026-05-01 19:45', 'Scheduled', 0, 0), # Leg 2
    ('EK202', 3, 2, '2026-05-02 10:00', '2026-05-02 18:00', 'Delayed', 45, 1),
    ('BA117', 4, 3, '2026-05-02 14:00', '2026-05-02 20:50', 'Scheduled', 0, 1),
    ('SQ634', 5, 5, '2026-05-03 13:55', '2026-05-03 20:45', 'On Time', 0, 1),
    ('TK182', 6, 6, '2026-05-03 09:00', '2026-05-03 12:30', 'Scheduled', 0, 1),
    ('PK302', 6, 10, '2026-05-04 18:00', '2026-05-04 19:50', 'Arrived', 10, 1),
    ('QR101', 7, 7, '2026-05-04 07:00', '2026-05-04 08:05', 'Scheduled', 0, 1),
    ('EK404', 8, 2, '2026-05-05 22:00', '2026-05-06 05:30', 'Scheduled', 0, 1),
    ('AF221', 10, 9, '2026-05-05 11:00', '2026-05-05 14:10', 'Scheduled', 0, 1)
]
cursor.executemany("INSERT INTO Flights (flight_number, route_id, aircraft_id, departure_time, arrival_time, status, delay_minutes, is_direct) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", flights_data)

# 6. Insert Passengers
passengers_data = [
    ('Zainab Abbas', 'PK123456', 'Pakistani', 'zainab@email.com'),
    ('John Smith', 'US987654', 'American', 'john.s@email.com'),
    ('Omar Khalid', 'PK554433', 'Pakistani', 'omar@email.com'),
    ('Mei Ling', 'SG112233', 'Singaporean', 'meiling@email.com'),
    ('Hakan Demir', 'TR778899', 'Turkish', 'hakan@email.com'),
    ('Alice Dubois', 'FR443322', 'French', 'alice@email.com'),
    ('Kenji Sato', 'JP009988', 'Japanese', 'sato@email.com'),
    ('Sara Ahmed', 'QA556677', 'Qatari', 'sara.a@email.com'),
    ('David Miller', 'UK667788', 'British', 'david.m@email.com'),
    ('Noor Fatima', 'PK221100', 'Pakistani', 'noor@email.com')
]
cursor.executemany("INSERT INTO Passengers (full_name, passport_number, nationality, email) VALUES (?, ?, ?, ?)", passengers_data)

bookings_data = [
    (1, 1, '12A', '2026-04-15', 'Business'),
    (1, 2, '12A', '2026-04-15', 'Business'),
    (2, 3, '45C', '2026-04-20', 'Economy'),
    (3, 1, '14B', '2026-04-10', 'Economy'),
    (4, 5, '01A', '2026-04-12', 'First'),
    (5, 6, '22D', '2026-04-22', 'Economy'),
    (6, 10, '05F', '2026-04-18', 'Business'),
    (7, 9, '10A', '2026-04-25', 'Business'),
    (8, 8, '03C', '2026-04-05', 'Economy'),
    (9, 4, '18A', '2026-04-28', 'Economy'),
    (10, 7, '20B', '2026-04-29', 'Economy')
]
cursor.executemany("INSERT INTO Bookings (passenger_id, flight_id, seat_number, booking_date, class) VALUES (?, ?, ?, ?, ?)", bookings_data)

# 8. Insert Crew_Assignments
crew_data = [
    (1, 1, 'Main Pilot'),
    (1, 2, 'Main Pilot'),
    (2, 1, 'Co-Pilot'),
    (3, 3, 'Main Pilot'),
    (4, 5, 'Main Pilot'),
    (5, 5, 'Co-Pilot'),
    (6, 10, 'Main Pilot'),
    (7, 4, 'Main Pilot'),
    (8, 7, 'Co-Pilot'),
    (9, 6, 'Main Pilot'),
    (10, 8, 'Co-Pilot')
]
cursor.executemany("INSERT INTO Crew_Assignments (pilot_id, flight_id, role) VALUES (?, ?, ?)", crew_data)

conn.commit()
print("Data successfully inserted.")

# ============================================================
# Fix 1 — Rename flight numbers to match test queries
# ============================================================

cursor.execute("UPDATE Flights SET flight_number = 'PK301' WHERE flight_number = 'PK301-A'")
cursor.execute("UPDATE Flights SET flight_number = 'PK302' WHERE flight_number = 'PK301-B'")
conn.commit()

# Verify the change
cursor.execute("SELECT flight_id, flight_number FROM Flights")
print("✅ Flight numbers updated:")
for row in cursor.fetchall():
    print(f"   {row}")

import pandas as pd

query3 = '''
SELECT
    f.flight_number,
    COUNT(b.booking_id) AS Total_Passengers,
    f.status
FROM Flights f
LEFT JOIN Bookings b ON f.flight_id = b.flight_id
GROUP BY f.flight_number
ORDER BY Total_Passengers DESC
'''

df_audit = pd.read_sql_query(query3, conn)
display(df_audit)