# -*- coding: utf-8 -*-
"""bscs25047, bscs25009_FPROJ_PHASE_04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cQ2Xl3cH3lpsalaIWbsX3YCyEn8YRj1N
"""

# Cell 1 — Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')
print("✅ Google Drive mounted.")

# Cell 2 — Connect to the airline database
import sqlite3

DB_PATH = '/content/drive/MyDrive/airline_management.db'

def get_connection():
    """Always returns a fresh connection to avoid disk I/O errors."""
    conn = sqlite3.connect(DB_PATH)
    conn.execute("PRAGMA foreign_keys = ON;")
    return conn

# Initial connection test
conn = get_connection()
cursor = conn.cursor()
print("✅ Connected to database:", DB_PATH)

# Cell 3 — Install Gradio
!pip install -q gradio
print("✅ Gradio installed.")

# Cell 4 — Install LangChain libraries
!pip install -q langchain
!pip install -q langchain-groq
!pip install -q langchain-core
print("✅ All libraries installed.")

# Cell 5 — Imports
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import SystemMessage, HumanMessage
import os
print("✅ All imports successful.")

# Cell 6 — Groq API key and LLM initialization
from google.colab import userdata
GROQ_API_KEY = userdata.get("GROQ_API_KEY")

llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    api_key=GROQ_API_KEY,
    temperature=0,
)
print("✅ Groq LLM initialized.")
print(f"   Model : {llm.model_name}")
print(f"   Temp  : {llm.temperature}")

# Cell 7 — Auto-generate DB schema from the live database
# Reads actual table and column names directly from the database
# so the LLM always sees the real structure — no invented columns

import sqlite3

def build_schema():
    conn = get_connection()
    cursor = conn.cursor()

    # Get all table names
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;")
    tables = [row[0] for row in cursor.fetchall()]

    schema_parts = []
    for table in tables:
        # Get exact column info from the live database
        cursor.execute(f"PRAGMA table_info({table});")
        columns = cursor.fetchall()

        # Get foreign key relationships
        cursor.execute(f"PRAGMA foreign_key_list({table});")
        fks = {row[3]: f"{row[2]}({row[4]})" for row in cursor.fetchall()}

        col_lines = []
        for col in columns:
            col_id, col_name, col_type, not_null, default, is_pk = col
            notes = []
            if is_pk:
                notes.append("PRIMARY KEY")
            if col_name in fks:
                notes.append(f"FOREIGN KEY → {fks[col_name]}")
            if not_null:
                notes.append("NOT NULL")
            note_str = "  (" + ", ".join(notes) + ")" if notes else ""
            col_lines.append(f"   - {col_name}  {col_type}{note_str}")

        schema_parts.append(f"Table: {table}\n" + "\n".join(col_lines))

    conn.close()
    return "\n\n".join(schema_parts)


DB_SCHEMA = f"""
You are working with a SQLite database for Flight Operations & Route Analytics.
Database name: airline_management.db

EXACT TABLE AND COLUMN DEFINITIONS (auto-generated from live database):
=======================================================================
{build_schema()}

VOCABULARY MAP:
===============
If the user says "clients", "travelers", or "people"     → use the Passengers table
If the user says "purchases", "tickets", "reservations"  → use the Bookings table
If the user says "crew", "staff", or "workers"           → use the Crew_Assignments table
If the user says "planes" or "jets"                      → use the Aircraft table
If the user says "trips", "journeys", or "paths"         → use the Routes table
If the user says "departures" or "arrivals"              → use the Flights table
"""

print("✅ DB_SCHEMA auto-generated from live database.")
print(DB_SCHEMA)

# Cell 8 — SQL generation function
def generate_sql(user_input):
    system_message = SystemMessage(content=f"""
You are a SQLite query generator for a Flight Operations database.

{DB_SCHEMA}

STRICT RULES:
1. Return ONLY the raw SQL query — no markdown, no backticks, no explanation.
2. Only generate SELECT statements. Never write INSERT, UPDATE, DELETE, DROP.
3. Use ONLY the exact table and column names shown in the schema above.
   Never invent or assume column names that are not listed there.
4. If the question cannot be answered, respond with exactly: CANNOT_ANSWER
5. Never fabricate data or assume values not in the schema.
6. For the class column in Bookings, always use exact capitalised values:
   'Economy', 'Business', 'First' — never lowercase.
7. For the status column in Flights, always use exact capitalised values:
   'Scheduled', 'Delayed', 'Cancelled', 'Completed' — never lowercase.
8. For the status column in Aircraft, always use exact capitalised values:
   'Active', 'Maintenance', 'Retired' — never lowercase.
9. For the rank column in Pilots, always use exact capitalised values:
   'Captain', 'First Officer', 'Co-Pilot' — never lowercase.
10. For the role column in Crew_Assignments, always use exact capitalised values:
    'Captain', 'First Officer', 'Co-Pilot' — never lowercase.
11. For the is_direct column in Flights, always use 1 for direct and 0 for
    connecting — never use TRUE, FALSE, 'yes', or 'no'.
12. When showing route origins or destinations, always JOIN with the Airports
    table using airport_id and show the city column — never return raw
    airport_id integers. Never invent columns like origin_city or destination_city.
    When joining Airports twice, always alias the table like this:
    JOIN Airports AS origin_ap   ON r.origin_airport_id = origin_ap.airport_id
    JOIN Airports AS dest_ap     ON r.destination_airport_id = dest_ap.airport_id
    Then use origin_ap.city and dest_ap.city in the SELECT.
13. When counting and also listing names together, use GROUP_CONCAT or a
    subquery — never mix COUNT() with individual name columns incorrectly.
""")
    human_message = HumanMessage(content=f"Question: {user_input}")
    response = llm.invoke([system_message, human_message])
    return response.content.strip()

print("✅ generate_sql() defined.")

# Cell 9 — Safe SQL execution function
def execute_sql(sql_query):
    # Block CANNOT_ANSWER
    if sql_query.strip().upper() == "CANNOT_ANSWER":
        return None, "I'm sorry, that question cannot be answered from the available data."

    # Block anything that isn't SELECT
    first_word = sql_query.strip().split()[0].upper()
    if first_word != "SELECT":
        return None, "⚠️ Blocked: Only SELECT queries are allowed."

    try:
        # Fresh connection every time — prevents disk I/O errors in Colab
        conn = get_connection()
        cursor = conn.cursor()
        cursor.execute(sql_query)
        rows = cursor.fetchall()
        columns = [description[0] for description in cursor.description]
        conn.close()

        if not rows:
            return None, "The query ran successfully but returned no results."

        return {"columns": columns, "rows": rows}, None

    except Exception as e:
        return None, f"⚠️ Database error: {str(e)}"

print("✅ execute_sql() defined.")

# Cell 10 — Response synthesis function
def synthesize_response(user_input, sql_query, result):
    columns = result["columns"]
    rows = result["rows"]

    formatted_result = f"Columns: {columns}\n"
    formatted_result += f"Total rows returned: {len(rows)}\n\nData:\n"
    for row in rows:
        row_dict = dict(zip(columns, row))
        formatted_result += f"  {row_dict}\n"

    system_message = SystemMessage(content="""
You are a helpful data analyst assistant.
Convert the raw database result into a clear, friendly plain English answer.

RULES:
1. Never say "the query returned" or use technical database terms.
2. Speak directly to the user in simple, natural language.
3. If multiple rows exist, summarize them clearly.
4. Never fabricate any data beyond what is provided.
5. Keep the answer concise but complete.
""")

    human_message = HumanMessage(content=f"""
The user asked: "{user_input}"
SQL used: {sql_query}

Raw results:
{formatted_result}

Write a clear plain English answer based strictly on the data above.
""")

    response = llm.invoke([system_message, human_message])
    return response.content.strip()

print("✅ synthesize_response() defined.")

# Cell 11 — Main pipeline function
def ask_question(user_input):
    """
    Input  : natural language question (string)
    Output : (plain_english_answer, sql_query) — both strings
    """
    # Stage 1: Generate SQL
    sql_query = generate_sql(user_input)

    # Handle CANNOT_ANSWER
    if sql_query.strip().upper() == "CANNOT_ANSWER":
        return "I'm sorry, that question cannot be answered from the available data.", "CANNOT_ANSWER"

    # Stage 2: Execute safely
    result, error = execute_sql(sql_query)
    if error:
        return error, sql_query

    # Stage 3: Synthesize plain English answer
    answer = synthesize_response(user_input, sql_query, result)
    return answer, sql_query


# Quick test — should print a real answer
answer, sql = ask_question("List all delayed flights")
print("✅ Pipeline working!")
print(f"\nAnswer: {answer}")
print(f"\nSQL: {sql}")

# Cell 12 — Phase 4 Gradio UI
import gradio as gr

custom_css = """
.gradio-container {
    background-color: #f0f9ff !important;
}

/* ── Nav pills (fixed width for alignment) ── */
.nav-pill {
    border-radius: 999px !important;
    border: 1.5px solid #7dd3fc !important;
    color: #0369a1 !important;
    background: white !important;
    font-weight: 500 !important;
    font-size: 13px !important;
    padding: 7px 0 !important;
    box-shadow: none !important;
    width: 110px !important;
    min-width: 110px !important;
    max-width: 110px !important;
    text-align: center !important;
    transition: box-shadow 0.18s !important;
}
.nav-pill:hover {
    box-shadow: 0 4px 14px rgba(6,182,212,0.28) !important;
    transform: translateY(-1px) !important;
    background: white !important;
    color: #0369a1 !important;
}
.nav-pill-active {
    border-radius: 999px !important;
    background: #0ea5e9 !important;
    color: white !important;
    border: 1.5px solid #0ea5e9 !important;
    font-weight: 500 !important;
    font-size: 13px !important;
    padding: 7px 0 !important;
    box-shadow: 0 4px 14px rgba(14,165,233,0.3) !important;
    width: 110px !important;
    min-width: 110px !important;
    max-width: 110px !important;
    text-align: center !important;
}

/* ── Action pills (Ask/Clear/Load Table) ── */
.action-pill {
    border-radius: 999px !important;
    background: #0ea5e9 !important;
    color: white !important;
    border: 1.5px solid #0ea5e9 !important;
    font-weight: 500 !important;
    font-size: 13px !important;
    padding: 7px 22px !important;
    box-shadow: 0 4px 14px rgba(14,165,233,0.3) !important;
}
.action-pill-sec {
    border-radius: 999px !important;
    border: 1.5px solid #7dd3fc !important;
    color: #0369a1 !important;
    background: white !important;
    font-weight: 500 !important;
    font-size: 13px !important;
    padding: 7px 22px !important;
    box-shadow: none !important;
}
.action-pill-sec:hover {
    box-shadow: 0 4px 14px rgba(6,182,212,0.28) !important;
    transform: translateY(-1px) !important;
}

/* ── Example buttons (full width, no squish) ── */
.example-btn {
    border-radius: 999px !important;
    border: 1.5px solid #7dd3fc !important;
    color: #0369a1 !important;
    background: white !important;
    font-weight: 500 !important;
    font-size: 13px !important;
    padding: 10px 22px !important;
    box-shadow: none !important;
    width: 100% !important;
    text-align: center !important;
    margin-bottom: 8px !important;
    transition: box-shadow 0.18s !important;
}
.example-btn:hover {
    box-shadow: 0 4px 14px rgba(6,182,212,0.28) !important;
    transform: translateY(-1px) !important;
}

/* ── Textbox styling ── */
.gradio-container textarea,
.gradio-container input[type="text"] {
    background-color: white !important;
    color: #0f172a !important;
    border: 1.5px solid #7dd3fc !important;
    border-radius: 8px !important;
}
.gradio-container label span {
    background-color: #0ea5e9 !important;
    color: white !important;
    border-radius: 6px !important;
    font-size: 12px !important;
}
.gradio-container .block,
.gradio-container .form,
.gradio-container .gap,
div[data-testid="textbox"],
div[data-testid="textbox"] > label {
    background: transparent !important;
    border: none !important;
    box-shadow: none !important;
    padding: 2px 0 !important;
}
.gradio-container textarea:focus,
.gradio-container input[type="text"]:focus {
    border-color: #06b6d4 !important;
    box-shadow: 0 0 0 3px rgba(6,182,212,0.15) !important;
    outline: none !important;
}
"""

with gr.Blocks(theme=gr.themes.Soft(), css=custom_css,
               title="AeroPath Operations & Analytics") as demo:

    # ── Header ─────────────────────────────────────────────
    gr.HTML("""
        <div style="
            background: linear-gradient(135deg, #0ea5e9, #06b6d4);
            padding: 20px 24px;
            border-radius: 10px;
            margin-bottom: 4px;
        ">
            <h1 style="color:white; font-size:22px; font-weight:500; margin:0;">
                ✈ AeroPath Operations & Analytics
            </h1>
            <p style="color:#e0f2fe; font-size:13px; margin:4px 0 0 0; opacity:0.9;">
                AI-Powered Flight Database Assistant —
                Ask anything about flights, routes, crew, or passengers
            </p>
        </div>
    """)

    # ── Nav pills ───────────────────────────────────────────
    gr.HTML("""
        <div id="nav-bar" style="
            display: flex;
            justify-content: center;
            align-items: center;
            gap: 10px;
            padding: 14px 0;
        ">
            <button id="fake-nav" style="display:none"></button>
        </div>
    """)
    with gr.Row():
        btn_chat     = gr.Button("Chat",     elem_classes="nav-pill-active")
        btn_examples = gr.Button("Examples", elem_classes="nav-pill")
        btn_debug    = gr.Button("Debug",    elem_classes="nav-pill")
        btn_about    = gr.Button("About",    elem_classes="nav-pill")
        btn_database = gr.Button("Database", elem_classes="nav-pill")

    # ── Chat panel ─────────────────────────────────────────
    with gr.Column(visible=True) as panel_chat:
        user_input = gr.Textbox(
            label="Ask a question about flights, passengers, or routes",
            placeholder="e.g. List all delayed flights",
            lines=2
        )
      with gr.Row():
        btn_chat     = gr.Button("Chat",     elem_classes="nav-pill-active")
        btn_examples = gr.Button("Examples", elem_classes="nav-pill")
        btn_debug    = gr.Button("Debug",    elem_classes="nav-pill")
        btn_about    = gr.Button("About",    elem_classes="nav-pill")
        btn_database = gr.Button("Database", elem_classes="nav-pill")

    # ── Examples panel ─────────────────────────────────────
    with gr.Column(visible=False) as panel_examples:
        gr.HTML("<h3 style='color:#0369a1; margin-bottom:12px;'>Click any question to load it into the Chat tab</h3>")
        ex1 = gr.Button("List all delayed flights",                         elem_classes="example-btn")
        ex2 = gr.Button("Which pilot has the most flight assignments?",     elem_classes="example-btn")
        ex3 = gr.Button("How many passengers travelled in Business class?", elem_classes="example-btn")
        ex4 = gr.Button("Which route has the highest average delay?",       elem_classes="example-btn")
        ex5 = gr.Button("What is the total number of bookings per class?",  elem_classes="example-btn")
        ex6 = gr.Button("List all active aircraft in the fleet",            elem_classes="example-btn")
        ex7 = gr.Button("Show me all flights departing from Karachi",       elem_classes="example-btn")

    # ── Debug panel ────────────────────────────────────────
    with gr.Column(visible=False) as panel_debug:
        sql_out = gr.Textbox(
            label="Generated SQL Query — last executed",
            lines=6,
            interactive=False,
            placeholder="The SQL query will appear here after you ask a question..."
        )

    # ── About panel ────────────────────────────────────────
    with gr.Column(visible=False) as panel_about:
        gr.HTML("""
        <div style="padding: 10px 4px;">
            <h3 style="color:#0369a1; font-size:18px; font-weight:600; margin-bottom:16px;">
                Domain: Flight Operations & Route Analytics
            </h3>
            <p style="color:#0f172a; font-size:14px; margin-bottom:8px;">
                <b style="color:#0f172a;">Course:</b> Database Systems CS-254 — ITU
            </p>
            <p style="color:#0f172a; font-size:14px; margin-bottom:8px;">
                <b style="color:#0f172a;">Student IDs:</b> BSCS25047 &amp; BSCS25009
            </p>
            <p style="color:#0f172a; font-size:14px; margin-bottom:16px; line-height:1.7;">
                This system uses a conversational AI pipeline powered by LangChain and
                Groq (llama-3.3-70b-versatile) to translate natural language questions
                into SQLite queries and return plain English answers.
            </p>
            <p style="color:#0f172a; font-size:14px; font-weight:600; margin-bottom:10px;">
                The database contains 8 tables:
            </p>
            <div style="display:grid; grid-template-columns:1fr 1fr; gap:8px; max-width:400px;">
                <div style="background:#e0f2fe; border:1px solid #7dd3fc; border-radius:8px;
                            padding:8px 14px; color:#0369a1; font-size:13px; font-weight:500;">Airports</div>
                <div style="background:#e0f2fe; border:1px solid #7dd3fc; border-radius:8px;
                            padding:8px 14px; color:#0369a1; font-size:13px; font-weight:500;">Aircraft</div>
                <div style="background:#e0f2fe; border:1px solid #7dd3fc; border-radius:8px;
                            padding:8px 14px; color:#0369a1; font-size:13px; font-weight:500;">Pilots</div>
                <div style="background:#e0f2fe; border:1px solid #7dd3fc; border-radius:8px;
                            padding:8px 14px; color:#0369a1; font-size:13px; font-weight:500;">Routes</div>
                <div style="background:#e0f2fe; border:1px solid #7dd3fc; border-radius:8px;
                            padding:8px 14px; color:#0369a1; font-size:13px; font-weight:500;">Flights</div>
                <div style="background:#e0f2fe; border:1px solid #7dd3fc; border-radius:8px;
                            padding:8px 14px; color:#0369a1; font-size:13px; font-weight:500;">Passengers</div>
                <div style="background:#e0f2fe; border:1px solid #7dd3fc; border-radius:8px;
                            padding:8px 14px; color:#0369a1; font-size:13px; font-weight:500;">Bookings</div>
                <div style="background:#e0f2fe; border:1px solid #7dd3fc; border-radius:8px;
                            padding:8px 14px; color:#0369a1; font-size:13px; font-weight:500;">Crew Assignments</div>
            </div>
        </div>
        """)

    # ── Database panel ─────────────────────────────────────
    with gr.Column(visible=False) as panel_database:
        gr.HTML("<h3 style='color:#0369a1; margin-bottom:12px;'>Browse Database Tables</h3>")
        table_selector = gr.Dropdown(
            choices=["Airports", "Aircraft", "Pilots", "Routes",
                     "Flights", "Passengers", "Bookings", "Crew_Assignments"],
            label="Select a table to view",
            value="Flights"
        )
        view_btn = gr.Button("Load Table", elem_classes="action-pill")
        table_out = gr.Dataframe(
            label="Table Data",
            interactive=False,
            wrap=True
        )

    # ── Define output lists ─────────────────────────────────
    panel_outputs = [panel_chat, panel_examples, panel_debug,
                     panel_about, panel_database]
    btn_outputs   = [btn_chat, btn_examples, btn_debug,
                     btn_about, btn_database]
    all_outputs   = panel_outputs + btn_outputs

    # ── Chat logic ─────────────────────────────────────────
    def run_query(question):
        if not question.strip():
            return gr.update(visible=False), "Please type a question first.", ""
        try:
            answer, sql = ask_question(question)
            return gr.update(visible=False), answer, sql
        except Exception as e:
            return gr.update(visible=False), "Something went wrong. Please try again.", ""

    def show_thinking():
        return gr.update(visible=True)

    def clear_all():
        return "", gr.update(visible=False), "", ""

    ask_btn.click(fn=show_thinking, outputs=[status_msg]).then(
        fn=run_query, inputs=[user_input],
        outputs=[status_msg, answer_out, sql_out]
    )
    clear_btn.click(fn=clear_all,
                    outputs=[user_input, status_msg, answer_out, sql_out])

    # ── Database logic ─────────────────────────────────────
    def load_table(table_name):
        try:
            conn = get_connection()
            cursor = conn.cursor()
            cursor.execute(f"SELECT * FROM {table_name}")
            rows = cursor.fetchall()
            columns = [desc[0] for desc in cursor.description]
            conn.close()
            import pandas as pd
            return pd.DataFrame(rows, columns=columns)
        except Exception as e:
            import pandas as pd
            return pd.DataFrame([["Error: " + str(e)]])

    view_btn.click(fn=load_table, inputs=[table_selector], outputs=[table_out])

    # ── Examples logic ─────────────────────────────────────
    def load_example(question):
        return (
            question,
            gr.update(visible=True),
            gr.update(visible=False),
            gr.update(visible=False),
            gr.update(visible=False),
            gr.update(visible=False),
            gr.update(elem_classes="nav-pill-active"),
            gr.update(elem_classes="nav-pill"),
            gr.update(elem_classes="nav-pill"),
            gr.update(elem_classes="nav-pill"),
            gr.update(elem_classes="nav-pill"),
        )

    ex_outputs = [user_input] + panel_outputs + btn_outputs

    ex1.click(fn=lambda: load_example("List all delayed flights"),                         outputs=ex_outputs)
    ex2.click(fn=lambda: load_example("Which pilot has the most flight assignments?"),     outputs=ex_outputs)
    ex3.click(fn=lambda: load_example("How many passengers travelled in Business class?"), outputs=ex_outputs)
    ex4.click(fn=lambda: load_example("Which route has the highest average delay?"),       outputs=ex_outputs)
    ex5.click(fn=lambda: load_example("What is the total number of bookings per class?"),  outputs=ex_outputs)
    ex6.click(fn=lambda: load_example("List all active aircraft in the fleet"),            outputs=ex_outputs)
    ex7.click(fn=lambda: load_example("Show me all flights departing from Karachi"),       outputs=ex_outputs)

    # ── Tab switching logic ────────────────────────────────
    def show_chat():
        return (gr.update(visible=True),  gr.update(visible=False),
                gr.update(visible=False), gr.update(visible=False),
                gr.update(visible=False),
                gr.update(elem_classes="nav-pill-active"), gr.update(elem_classes="nav-pill"),
                gr.update(elem_classes="nav-pill"),        gr.update(elem_classes="nav-pill"),
                gr.update(elem_classes="nav-pill"))

    def show_examples():
        return (gr.update(visible=False), gr.update(visible=True),
                gr.update(visible=False), gr.update(visible=False),
                gr.update(visible=False),
                gr.update(elem_classes="nav-pill"),        gr.update(elem_classes="nav-pill-active"),
                gr.update(elem_classes="nav-pill"),        gr.update(elem_classes="nav-pill"),
                gr.update(elem_classes="nav-pill"))

    def show_debug():
        return (gr.update(visible=False), gr.update(visible=False),
                gr.update(visible=True),  gr.update(visible=False),
                gr.update(visible=False),
                gr.update(elem_classes="nav-pill"),        gr.update(elem_classes="nav-pill"),
                gr.update(elem_classes="nav-pill-active"), gr.update(elem_classes="nav-pill"),
                gr.update(elem_classes="nav-pill"))

    def show_about():
        return (gr.update(visible=False), gr.update(visible=False),
                gr.update(visible=False), gr.update(visible=True),
                gr.update(visible=False),
                gr.update(elem_classes="nav-pill"),        gr.update(elem_classes="nav-pill"),
                gr.update(elem_classes="nav-pill"),        gr.update(elem_classes="nav-pill-active"),
                gr.update(elem_classes="nav-pill"))

    def show_database():
        return (gr.update(visible=False), gr.update(visible=False),
                gr.update(visible=False), gr.update(visible=False),
                gr.update(visible=True),
                gr.update(elem_classes="nav-pill"),        gr.update(elem_classes="nav-pill"),
                gr.update(elem_classes="nav-pill"),        gr.update(elem_classes="nav-pill"),
                gr.update(elem_classes="nav-pill-active"))

    btn_chat    .click(show_chat,     outputs=all_outputs)
    btn_examples.click(show_examples, outputs=all_outputs)
    btn_debug   .click(show_debug,    outputs=all_outputs)
    btn_about   .click(show_about,    outputs=all_outputs)
    btn_database.click(show_database, outputs=all_outputs)

demo.launch(share=True)